### ISSUE TITLE
antergos-notify.sh does not work with usernames longer than 7 characters

### ISSUE THREAD

**Issue by sebva** [Antergos/antergos-alerts#5]
Hello, I am encountering a problem that happens when pacman executes the `antergos-reboot.hook` hook. As such, when the hook executes, I get the following message (my username is `sebastien`):
```
nologin: invalid option -- 'c'
Try 'nologin --help' for more information.
su: user sebasti+ does not exist
```

It seems that the problem lies in [antergos-notify.sh at line 38](https://github.com/Antergos/antergos-alerts/blob/3bb735cdcc86d24a9f742291d122a70ddb27c958/src/antergos-notify.sh#L38). The output of `ps aux` truncates usernames to 7 characters.

**Comment by lots0logs** [comment]
Fixed in #6
